import MobileModule from "./module/MobileModule.js";
import AosModule from "./module/AosModule.js";
import BtnToTopModule from "./module/BtnToTopModule.js";
import PopupModule from "./module/PopupModule.js";
import SwiperModule from "./module/SwiperModule.js";
import CountUpModule from "./module/CountUpModule.js";
import SearchModule from "./module/SearchModule.js";
import Select2Module from "./module/Select2Module.js";
import GalleryModule from "./module/GalleryModule.js";
import TabModule from "./module/TabModule.js";
import HeaderModule from "./module/HeaderModule.js";
import SideModule from "./module/SideModule.js";
import CollapseModule from "./module/CollapseModule.js";
import ScrollTriggerModule from "./module/ScrollTriggerModule.js";
import ComponentModule from "./module/ComponentModule.js";
import DatePickerModule from "./module/DatePickerModule.js";
import SmoothScrollModule from "./module/SmoothScrollModule.js";

window.addEventListener("DOMContentLoaded", () => {
  ScrollTriggerModule();
  AosModule();
  TabModule();
  DatePickerModule();
  Select2Module();
  CountUpModule();
  SwiperModule();
  MobileModule();
  BtnToTopModule();
  HeaderModule();
  PopupModule();
  GalleryModule();
  SearchModule();
  SideModule();
  CollapseModule();
  ComponentModule();
  SmoothScrollModule();
});
